---
- rule:
    paths: "documentation/**"
    reviewers:
      - ruowan
      - raych1

- rule:
    paths: "specification/**/Microsoft.Network/**"
    reviewers:
      - ruowan
      - NullMDR
      - Dreamgoing

- rule:
    paths: 
      - "specification/@(containerservice|databricks|containerregistry|compute)/**"
      - "specification/@(docker)/**"
    reviewers:
      - ruowan
      - Dreamgoing

- rule:
    paths: "specification/**/date-plane/**"
    reviewers:
      - Dreamgoing

- rule:
    paths: 
      - "specification/**/resource-manager/**"
    reviewers:
      - NullMDR
      - ruowan

- rule:
    paths: 
     - "**/package.json"
     - "package.json"
    reviewers:
      - ruowan

- rule:
    paths: "**"
    reviewers:
      - yungezz
      - zikalino
      - erich-wang
      - NullMDR
      - raych1
      - lirenhe
      - weidongxu-microsoft
      - ArcturusZhang
      - xccc-msft
      - ChenTanyi
      - fengzhou-msft
      - njuCZ
      - akning-ms
      - markcowl
      - leni-msft
      - qianwens
      - ruowan
